Update testpublishrelease.yml

diff --git a/.github/workflows/testpublishrelease.yml b/.github/workflows/testpublishrelease.yml
--- a/.github/workflows/testpublishrelease.yml
+++ b/.github/workflows/testpublishrelease.yml
@@ -22,18 +22,29 @@ jobs:
     runs-on: ubuntu-latest
     timeout-minutes: 10
     steps:
-      - name: Test with input from workflow
-        run: |
-          echo "GITHUB_TAG_MAJOR_VERSION=${{ github.event.inputs.version }}" >> ${GITHUB_ENV}
-          exit 1
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
-
-      - name: Set with input from the PR title.
+      - name: Set Version from the PR title.
         if: github.event_name == 'pull_request'
         run: |
           echo "GITHUB_TAG_MAJOR_VERSION=${{ github.event.pull_request.title }}" >> ${GITHUB_ENV}
-          
-   publish-release:
+
+      - name: Major Version in Upgrade Handler Must Match Tag
+        if: github.event_name == 'pull_request'
+        run: |
+          UPGRADE_HANDLER_MAJOR_VERSION=$(cat app/setup_handlers.go | grep "const releaseVersion" | cut -d ' ' -f4 | tr -d '"')
+          echo $UPGRADE_HANDLER_MAJOR_VERSION
+          echo $GITHUB_TAG_MAJOR_VERSION
+          if [ $GITHUB_TAG_MAJOR_VERSION != $UPGRADE_HANDLER_MAJOR_VERSION ]; then
+            echo "ERROR: The major version of this release (${{ github.ref_name }}) does not match the major version in the releaseVersion constant ($UPGRADE_HANDLER_MAJOR_VERSION) found in app/setup_handlers.go"
+            echo "Did you forget to update the 'releaseVersion' in app/setup_handlers.go?" 
+            exit 1
+          fi
+          echo "The major version found in 'releaseVersion' in app/setup_handlers.go matches this tagged release - Moving Forward!"
+
+  publish-release:
     runs-on: buildjet-4vcpu-ubuntu-2004
     timeout-minutes: 60
     needs:
